### ISSUE TITLE
First Thursday is not always after first Monday

### ISSUE THREAD

**Issue by bradyt** [tippenein/BankHoliday#1]
You have `firstThursdayIn month = addDays 3 (firstMondayIn month)`, but for example, Thursday, January 2nd, 2020, is not after Monday, January 6th, 2020.

**Comment by bradyt** [comment]
So then with ```, 2 `weeksAfter` firstThursdayIn nov -- thanksgiving```, I think the issues cancelled each other out for 2016, 2017, 2018.

**Comment by tippenein** [comment]
This looks like it was fixed by @catdarick in that fork so I'll close this now
